README.md, slack-buffer.el
Hi,
I ran into your project through [this](https://www.reddit.com/r/emacs/comments/3uqork/someone_is_working_on_another_slack_client/) reddit thread. I've been wanting to try and write an Emacs Slack client for awhile and just felt like I could get around to it when I read that thread. So I immediately tried out your client.
It was a bit of a challenge. First trying to find out where to find the client id and secret and the token, which would have been much easier if I'd paid more attention to the README. And then how to send a message. `M-x slack-message-send RET My message C-j` is not exactly my idea of a frictionless workflow. It was also a bit strange to find that `RET` in the minibuffer added a newline instead of sending the message.
Anyway, I thought that it would be great to have a …
=> Use Linewise User Interface for Slack rooms

slack-pkg.el, slack.el
Hi again,
I use `package.el` for all my package installations, and it'd be great if emacs-slack could support this as well. This greatly simplifies installing and testing this package and in the future will help to get this package into repositories like Melpa, if you're interested in that.
I've added a single autoload, because as I think `slack-start` is the only real entry point into this package, but if there are others, please let me know and I'll add them.
I've picked version 0 for this package to start with to indicate that no releases have been made yet. When you feel comfortable releasing/tagging a first version we should change this. I'm partial to using [Semantic Versioning](http://semver.org/), but it is of course your call.
For the dependencies I've taken the latest I found on …
=> Add package definition

slack-message.el, slack-room.el
cl-defmethod and cl-defgeneric are implemented only in development Emacs.
So to use them causes error("no such function") on older Emacs.
I got following error when I loaded slack.el.
```
slack.el:31:1:Error: Symbol's function definition is void: cl-defgeneric
```
=> Fix for older Emacs

slack-buffer.el, slack-room.el
This fixes following byte-compile warnings.
```
In end of data:
slack-room.el:287:1:Warning: the function `first' is not known to be defined.
In end of data:
slack-buffer.el:154:1:Warning: the following functions are not known to be define\
d: first
```
=> Use cl-lib macro instead of cl.el

slack-buffer.el, slack-message-formatter.el, slack-message.el, slack-pkg.el, slack-room.el, slack-user-message.el
Hi,
As discussed in a previous pull request I was able send a patch to the Circe maintainer that allows us to change the time stamp lui outputs when inserting a message.
This change is only available in the latest git revisions of Circe and hasn't been officially released yet. I've upped the minimum required version in the pkg file to reflect that the next version released will be required. This should be fine for Melpa right now since any Melpa version should be higher than 2.2. Anyone using Melpa Stable instead would have trouble since 2.2 isn't on there yet. This shouldn't be an issue right now since there are no tags in this project yet, so it shouldn't show up on Melpa Stable.
I removed the time stamp from the message header because I didn't see the point in showing it twice.
I also …
=> Bind lui-time-stamp-time when inserting messages in a buffer

slack-bot-message.el, slack-message-formatter.el
Hi,
Certain bot messages (namely those from the Pivotal Tracker integration) don't specify a text and only offer text from attachments. When this happens the text slot is unbound and `with-slots` fails to get the
`text` slot.
Alternatively I could set the `:initform` of the `slack-message` class, but having tried that I get an error that there is no applicable method of `slack-message-notify-buffer` for `slack-bot-message`. I got this change done first, but if you prefer the other I'll change it.
=> Handle bot messages without text

slack-pkg.el
This will add to package information the URL. e.g.
```
slack is an available package.
Status: Available from sandbox -- [Install]
Archive: sandbox
Version: 20160513.1710
Requires: websocket-1.5, request-0.2.0, oauth2-0.10, circe-2.2, alert-1.2, emojify-0.2
Summary: Slack client for Emacs
Homepage: https://github.com/yuya373/emacs-slack
Other versions: 20160422.908 (melpa).
```
=> Add url description

README.md
This fixes obsolete variable in README.
=> Fix README: Not slack-enable-emoji but slack-buffer-emojify

slack-message-formatter.el, slack-message-sender.el
- Escape '<>&' in outgoing messages.
- Link @-references to users & #-references to channels.
This is taken from the Slack API docs at https://api.slack.com/docs/formatting. It doesn't do anything about bang-commands (e.g. <!here>).
=> Escape & link messages

slack-message-notification.el
This happens when there's no message body.
It might be smart to use the message attachments, if any.  For now
though, let's do the easy thing.
This addresses #124
=> Fix stringp warning

slack-team.el
This PR fixes a typo when prompting for the client secret.
=> Fix typo on prompt for client secret

slack-buffer.el
replace `<http://foobar.com|foobar>` with `foobar` clickable button.
=> add `slack-buffer-buttonize-link` to `lui-pre-output-hook`

slack.el
- hash-table-keys which is defined in subr-x.el was introduced at Emacs 24.4.
- And load subr-x in slack.el
=> Update minimum Emacs version

slack-buffer.el, slack-message-sender.el, slack-room.el, slack-websocket.el, slack.el
If one uses osd notifications she wouldn't ever find out if she was notified on channel if buffer is not open. This patch fixes it.
=> on buffer update, create buffer if it doesn't yet exist

slack-buffer.el
I've been looking at the functions responsible for creating and filling the buffers. `slack-buffer-widen` also uses `save-excursion`, and it seems that all the text insertion functions in turn use `slack-buffer-widen`, so point is never advanced beyond `(point-min)`.
I think this might also fix #128
---
This way users don’t have to move the cursor to the end of the buffer
themselves. Going to ‘(point-max)’ works just as well, but it seems
more accurate to go to the ‘lui-input-marker’, since we want users to
be able to start typing immediately.
=> Go to the input marker after setting up a buffer

slack-group.el, slack-im.el, slack-message-notification.el, slack-room.el, slack.el
Few more things I was missing:
1. basic mpim support
2. few titles are configurable (team name in front of every room is quite annoying)
3. im rooms are always open so it's not required to open them by hand. All im's are listed in slack-room-select right away
4. fix for background buffer creation when history load is required.
=> basic mpim support + some additional configurability

slack-message.el
these were missing after 78543435b8095329d22dfc8939db61c668896682
=> add object name to  constructor calls for file messages

slack-message-formatter.el
Sometimes SLACK-MESSAGE-TIME-TO-STRING gets called with a string and
sometimes it gets called with a number; calling STRING-TO-NUMBER on a
string results in an error.
It'd be nice to fix the underlying reason why it sometimes gets a
string and sometimes a number …
=> Fix bug with attachments in chats

slack-channel.el, slack-group.el, slack-im.el, slack-message-delete.el, slack-message-editor.el, slack-room.el, slack-websocket.el, slack.el
ref. #166 
- add `slack-display-team-name` default value is `t`
=> Configure display team name

slack-file.el
This is useful because some `completing-read` replacements don't let you submit an empty string unless it was specified as a completion option.
=> Specify "" as an actual completion option in `select-channels`

slack-message-notification.el, slack-message-update.el, slack-team.el, slack-websocket.el, slack.el
close #177 
add custom variables
- `slack-modeline-formatter` 
- function takes argument like `'((team-name . unread-count) ... )`
- `slack-modeline-count-only-subscribed-channel`
- default `t`. if `nil` count all channel's unread-count.
add team configurations
- `modeline-enabled`
- default `nil`. set this `t` if you want to show unread-count at modeline.
- `modeline-name`
- default `nil` name displayed at modeline. if nil, use team name from slack server.
=> add modeline unread count

slack-message-sender.el
It was incorrectly matching ':', '/' &c.
=> Update regexp to not match incorrect characters

slack-message-editor.el
A small fix to avoid error message on edit window close in case it was using whole frame
=> only delete editor window if there are more windows in frame

slack-bot-message.el, slack-file.el, slack-message-formatter.el, slack-room-history.el, slack-team.el, slack-user.el, slack-util.el
display profile image
- `slack-profile-image-file-directory`
- default: `temporary-file-directory`
- if you want profile image persisted, set some directory.
- `display-profile-image`
- default: `nil`
- this variable scope is team. set `t` to display image.
```
(slack-register-team
:default t
:name  "aaaaa"
.....
:display-profile-image t)
```
=> Profile image

slack-util.el
Right now company-mode completion will display deleted users; this patch hides them.
=> Hide deleted users

README.md
Might not work in the future, but it definitely does right now, and is a hell of a lot easier than creating an OAuth app
=> An easier way to get a token

slack-pkg.el, slack.el
In older version `websocket-open` does not accept `:nowait` arg.
=> Update websocket library to version 1.8

slack-util.el
This fixes this issue: https://github.com/yuya373/emacs-slack/issues/229
In this fix: the sorting of the concated images are now different depending on the system-type.
=> Fix for slack-mapconcat-images sorting issue.

slack-file.el
All other usages in the package use `cl-remove-if'. This one must have slipped by somehow.
=> Fix unbound function in file-upload

slack-bot-message.el
This looks for a bot username in `m` before using the default name for
that bot. In my experience, that better reflects the behaviour of the
web app.
=> Prefer the bot name provided in the message

slack-team.el
https://api.slack.com/docs/oauth
I wondered why I could not register multiple teams. There is no need to register a
client-id for each team.
The client-id is used to identify/auth apps (like Emacs in this case)
not teams. So it can be used for multiple teams.
=> Use token instead of client-id to check equalp of teams

slack-websocket.el
fixes error:
Error running timer: (void-variable team)
=> pass team to slack-notify-abandon-reconnect

slack-thread.el
Fixes error:
"command-execute: Wrong type argument: commandp, slack-thread-show-messages"
=> map RET to slack-thread-show-or-create

slack-buffer.el
I was getting this warning:
```
user-error: No more buttonsInvalid face attribute :wight bold
Invalid face attribute :wight bold [39 times]
```
Here's the fix.
=> fix typo `wight` to `weight`

README.md, slack-im.el, slack-message-formatter.el, slack-team.el, slack-user.el
close #258 
add `full-and-display-names` to team property. default `nil`.
nil means Just display names.
[![Screenshot from Gyazo](https://gyazo.com/2c61460546dd14344c93ef114c6309b9/raw)](https://gyazo.com/2c61460546dd14344c93ef114c6309b9)
=> add full-and-display-names

README.md
Just small patch for a link in the readme.
=> Fix "how to get token" link in README

slack-message-formatter.el
fix Debugger entered--Lisp error: (error "Invalid use of ‘\\\’ in replacement text")
=> use literary t

slack-channel.el, slack-group.el, slack-im.el, slack-request-worker.el, slack-request.el, slack-room.el, slack-team.el, slack-util.el, slack-websocket.el, slack.el
inhibit making a lot of connection when booting.
```
(defcustom slack-request-worker-max-request-limit 30
"Max request count perform simultaneously."
:group 'slack)
```
this variable limiting number of connection when using `slack-request-worker`.
currently this worker is used to fetch channel(group, im) list and information of each channels when booting.
=> Request worker

README.md
A small update to the README that points out that users can generate legacy API tokens.
=> Add another "Easy Way" of token generation

slack-message-formatter.el, slack-util.el
- parse `<!date...> ` and display time string.
- add custom variable `slack-date-formats`
token(date_short_pretty) in `slack-date-formats` is written "Formatting dates" section in https://api.slack.com/docs/message-formatting
=> escape <!data...> format

slack-thread.el
This allows the user to configure whether thread messages should
default to thread-only or room-too. The default behaviour (ask every
time) is preserved.
=> Add a defcustom slack-thread-also-send-to-room

slack-team.el, slack-websocket.el
stop reconnect when call `slack-ws-close` interactively
=> Fix ws close

slack-util.el
Resolves problems observed in #285 when emacs is being used without a graphical system (terminal).
=> Check for graphic display before rendering image

slack-message.el
close #334 
Slack's server send me `type: message` json in addition to `reply_to` json.
This will cause the message to be drawn twice in the buffer.
```
[2018-08-17 18:25:20] (:type message :user U838383 :text fuga :team T83838383 :channel D838383 :event_ts 1534497919.000100 :ts 1534497919.000100)
[2018-08-17 18:25:20] (:ok t :reply_to 16847 :ts 1534497919.000100 :text fuga)
```
=> check message exists or not

helm-slack.el, slack-authorize.el, slack-conversations.el, slack-file-list-buffer.el, slack-file.el, slack-message-buffer.el, slack-message-formatter.el, slack-message.el, slack-pinned-item.el, slack-pinned-items-buffer.el, slack-room.el, slack-search.el, slack-slash-commands.el, slack-star.el, slack-team.el, slack-thread.el, slack-user.el, slack-util.el, slack-websocket.el
instead of retrieve all users in workspace, call `users.info` with user ids
close #383 
close #388
=> Ondemand user info

slack-buffer.el, slack-message-reaction.el, slack-message.el, slack-reaction.el, slack-user.el
close #393 
- slack limited `users` to 30 query in some account.
- remove reacted users from prefetch
- fetch reacted users when display
=> Limit users query params

slack-request.el
When running emacs-slack on Windows with curl backend lots of these errors are present:
curl: (1) Protocol 'http not supported or disabled in libcurl
Changing the single quotes to escaped double quotes as Windows doesn't handle
single quotes in arguments very well.
See:
https://stackoverflow.com/questions/6884669/curl-1-protocol-https-not-supported-or-disabled-in-libcurl
=> Fix: curl: (1) Protocol 'http not supported or disabled in libcurl

slack-emoji.el
Doing `slack-user-set-status` gives `Command attempted to use
minibuffer while in minibuffer` if you've never used emojify
before. It seems it's because emojify wants to ask me whether I should
download emojis, but we're already using the minibuffer for
completing-read.
=> Check whether to download emoji before trying to complete on them

slack-util.el
I have `(setq slack-completing-read-function #'ivy-completing-read)`
I tried `slack-file-upload` and selected file and room – then it asks for
"Select another channel (or leave empty): "
but since it's configured to require a match, I can't leave it empty.
Users could work around this with
`(setq slack-completing-read-function
#'ivy-completing-read-with-empty-string-def)`
but then you get that completion function for *all* slack completion,
which we don't want. So instead, use an empty string def in
`slack-select-multiple`.
=> Empty string as default in slack-select-multiple

slack-emoji.el
Slack apparently allows recursive aliasing of emojis. Emoji downloads fail silently if this occurs. This PR should handle that, plus aliases that don't actually have a referent (we then just fall back on the slack emoji itself)
Addresses https://github.com/yuya373/emacs-slack/issues/414
=> Handle recursive emoji aliases, including dead-ends

slack-bot.el, slack-channel.el, slack-conversations.el, slack-group.el, slack-im.el, slack-message-buffer.el, slack-message-formatter.el, slack-message.el, slack-team.el, slack-thread.el, slack-user.el
close #418 
- add `visible-thread` to options
- add `slack-vislble-thread-sign` 
```emacs-lisp
(slack-register-team
:default nil
:name "emacs-slack"
;; snip
:visible-threads t
)
```
```emacs-lisp
(defcustom slack-visible-thread-sign ":left_speech_bubble: "
"Used to thread message sign if visible-threads mode."
:type 'string
:group 'slack)
```
=> Visible threads

slack-event.el, slack-message-event.el, slack-reaction-event.el, slack-star-event.el, slack-thread-event.el
ignore events received before room fetched for slow network or any other
reason
=> Ignore event when room not found

slack-file.el
I don't know if this'll solve all instances of potential problems but, per @umairbinaltaf and my own experiences, at least part of the issue that's run into by Mac users is the file not being expanded (e.g. `~` instead of `/Users/<user>/`) which causes the file upload to fail.
Expanding the file path has fixed every issue I've run into so suggesting this as, at the very least, a partial fix for #477.
=> Add Expanding the File Path to Aid Mac Users Using `curl`.

slack-team-ws.el
This limits the hang when emacs-slack tries to, unsuccessfully, reconnect.
=> make reconnect-count-max configurable

slack-request.el
Download file url and name are slack server-side controlled, thus there exists some potential for a malicious (or insufficiently filtering) slack server to provide potentially non-sanitized input to the curl download routines. By moving from start-process-shell-command to start-process for asynchronous curl downloads we reduce remote attack surface and limit the potential for shell escape and command injection vulnerabilities.
=> remove potential shell escape attack surface from curl downloader

README.md
I was motived by the discussion in #51 as well as a similar discussion on Reddit in r/emacs.  This PR does two things:
1. Inlines the instructions how to get your Slack token as the existing instructions were no longer valid
2. Provides a little more guidance how to secure your token via the Emacs `auth-source` package.
Clearly this is only an outline. A full `auth-source` tutorial would be out of scope for this readme. However, the idea is to provide enough guidance to help people get on the right track.
=> update documentation how to get and store tokens

slack-message-buffer.el, slack-message-notification.el
The tracking library accepts the specification of one or more faces to
use in its mode-line notifications.  This commit adds the ability to
tell slack to include user-defined faces when using the tracking
library.
I'm not sure if i've put the customize definition in the right module,
but it's very easy to move around.
=> Customizable faces for tracking mode-line notifications

slack-image.el
I use emacs-slack with Emacs 27.0.01 on Microsoft Windows and sometimes, some images refuse to load.  The issue was that the channel contained images with urls like http://example.com/image.jpg?crop=1:2;3:4.  The ':' in extension would get included in the cache path name, but ':' is a reserved character on that platform.
This patch tries to keep the file extension, while hiding the URL query string that follows it.
=> Avoid cache file names with illegal characters

slack-message-sender.el
It previously showed @channel instead of #channel.
I tested by eval'ing the function and trying it once.  I saw that the resulting message displayed correctly and that clicking the mention jumped me to the right channel, both in emacs slack and on the Android client.  Let me know if you'd like more testing.
=> Fix display text from slack-message-embed-channel

README.md, slack-request.el, slack-team.el, slack.el
This PR adds support and documentation for how to get a `d=` cookie that is
required for `xoxc` tokens. This may or may not be related to two other issues
#431 and #481 that mention trouble related to `xoxc` tokens.
=> Add support for cookie with `xoxc` token

slack-conversations.el
This is related to #504, and changes the default behavior when
updating channels to filter out archived channels.
=> Add flag to default to filtering archived channels

slack-util.el
and be missing `thread_ts=`. I don't know if `slack-info-to-permalink` should be changed the same way. 
I get these links from slack on unread messages, I can now click them since I have
```
(add-to-list 'browse-url-handlers (cons "^https://[^/]*.slack.com/\\(.*/\\)?archives/.*"
(lambda (url &rest ignored) (slack-open-url url))))
```
(emacs-slack might want to put that in browse-url-default-handlers?)
=> slack permalinks can have stuff before /archives/

slack-file.el
This simply makes the "Download..." button work in more traditional way where it let's user select where to save and then opens the directory in dired, focusing the newly downloaded file.
Also gets rid of the `:sync t` parameter where it was effectively not working in case of using _curl downloader_ (and I believe async is better for downloading files).
---
The new behavior is a bit opinionated but I believe this is what most of the users want. Maybe if you think it's too invasive then I can add an option or convert into a hook and let users decide what happens after the download.
=> Ask user where to download the file and open directory afterwards
