slack-message.el, slack-room.el, slack-websocket.el
fix text was not decoded when receive edited message.
=> Fix edited message

README.md, slack-message-sender.el
add `slack-message-embed-channel` and update README
=> Add embed channel

slack-message-editor.el, slack-message-sender.el, slack-request.el, slack-room.el, slack-user-message.el, slack.el
=> Add message edit feature

slack-buffer.el, slack-message-editor.el, slack-message-formatter.el, slack-message-reaction.el, slack-message.el, slack-reaction.el, slack-room.el, slack-user-message.el, slack.el
can adding reactions to message, removing reactions from message, show reactions with message.
=> Add reactions feature

slack-bot-message.el, slack-buffer.el, slack-message-editor.el, slack-message-reaction.el, slack-message.el
using replace with text-property 'ts instead of string search.
=> Fix slack buffer replace

README.md, slack-bot-message.el, slack-message-notification.el, slack-message.el, slack-pkg.el, slack-user-message.el
use [alert](https://github.com/jwiegley/alert) for notification instead of popup
=> Fix notification

slack-buffer.el, slack-channel.el, slack-group.el, slack-im.el, slack-message-notification.el, slack-message-reaction.el, slack-message-sender.el, slack-message.el, slack-room.el
show unread count in select list
insert only difference of messages from `last-read` attribute in room.
=> Unread count

slack-bot-message.el, slack-buffer.el, slack-room.el, slack-websocket.el
impl reaction_added, reaction_removed events
=> Reaction event

slack-buffer.el, slack-channel.el, slack-group.el, slack-im.el, slack-message-sender.el, slack-message.el, slack-room.el, slack-user.el, slack-websocket.el, slack.el
add channel, group operation and event.
=> Channel operation

slack-message-sender.el
=> add here and channel to mentions

slack-websocket.el
=> ignore reaction with not loaded messages

slack-room.el
=> fix slack-room-load-prev-messages

slack-websocket.el
=> fix slack-ws-handle-reaction

slack-message.el
=> add nil guard to slack-room-find

slack-buffer.el, slack-message-notification.el, slack-message.el
- add kill-buffer-hook
- remove slack notification buffer
=> remove slack notification buffer & add slack-reset-last-read to kill-buffer-hook

slack-bot-message.el, slack-message.el
=> init attachment field fallback with nil

slack-message-sender.el, slack-reply.el, slack-room.el, slack-websocket.el
fix #57 
- reduce timeout interval
- buffer un send messages
- resend bufferd messages when connect websocket
=> Fix slack message sending

slack-buffer.el
=> fix slack-reset-room-last-read

slack-room.el
=> fix object constructor param

README.md, slack-bot-message.el, slack-buffer.el, slack-channel.el, slack-file.el, slack-group.el, slack-im.el, slack-message-editor.el, slack-message-formatter.el, slack-message-notification.el, slack-message-reaction.el, slack-message-sender.el, slack-message.el, slack-reaction.el, slack-reply.el, slack-request.el, slack-room.el, slack-team.el, slack-user-message.el, slack-user.el, slack-websocket.el, slack.el
=> Multiple team

slack-buffer.el
=> move up macro definition

slack-team.el, slack.el
=> fix slack-register-team

slack-team.el, slack-websocket.el
=> Show typing indicator

slack-team.el
=> add require slack-util

slack-buffer.el, slack-websocket.el, slack.el
close #86 
add `slack-typing-visibility` to configure typing indicator
=> Conf typing indicator

README.md, slack-buffer.el
add
- slack-buffer-goto-next-message
- slack-buffer-goto-prev-message
- slack-buffer-goto-first-message
- slack-buffer-goto-last-message
=> add slack-buffer-goto-(next|prev|first|last)-message

slack-util.el
This is a lightweight company-mode backend which adds user completion to slack. Adding channel completion should be relatively easy too.
It doesn't yet support @here.
=> Add company backend for slack

slack-message-formatter.el, slack-reminder.el, slack-team.el, slack-websocket.el, slack.el
=> Add reminder

slack-message-reaction.el
=> completing-read with emojify emojis

slack-team.el, slack-websocket.el
fix #119
workaround for :initform
=> remove ping-check-timers :initform

slack-buffer.el, slack-message.el, slack-search.el
**This pull request can't be merged yet**, it requires that jorgenschaefer/circe#270 be merged first. However I thought it might be useful to have this up already so you can see what's been done and give any feedback you think appropriate.
So this is the possible future implementation of having `lui.el` take care of message editing and deleting, instead of having to do it ourselves. Sorry it's taken me so long, I've been sitting on it for a while now.
=> Offload editing to lui

slack-message-formatter.el, slack-message-reaction.el, slack-message.el
=> Fix slack file message missing reactions

slack-bot-message.el, slack-channel.el, slack-file.el, slack-message-editor.el, slack-message-formatter.el, slack-message-sender.el, slack-message.el, slack-room.el, slack-websocket.el
=> Handle file comment

slack-file.el
Another instance of this emacs 24 constructor issue
=> add object name to constructor calls for files (required for emacs 24)

slack-group.el
close #157 
add missing argument `team`
=> fix `slack-group-list-update`

slack-thread.el, slack-websocket.el
add `slack-room-unread-threads`
=> Add slack-room-unread-threads

slack-file.el, slack-group.el, slack-message-reaction.el, slack-message-sender.el, slack-room.el, slack-search.el, slack-team.el, slack.el
- add `slack-completing-read-function` default value is `completing-read`
=> Configure completing read function

slack-im.el, slack-message-reaction.el, slack-request.el, slack-user-message.el, slack-user.el, slack-websocket.el
- set status emoji and status text by `slack-user-set-status`
=> User status

slack-message.el
=> convert ts if number to string

slack-message-delete.el
close #187 
add custom variable `slack-message-custom-delete-notifier`.
=> Add user delete notification

slack-im.el, slack-user.el, slack-websocket.el
- fix team_joined handler
- add member_joined_channel handler
- add member_left_channel handler
=> Fix user joined

README.md
Just some misc updates to the README on things I thought weren't that clear, but got it up and running so that's good! Thanks.
=> Misc documentation update

slack-util.el
=> Fix sort function

slack-message-sender.el
=> Fix embed mention

slack-message-changed.el
=> fix message changed event to slack-file-message

slack-websocket.el
=> Cancel reconnect timer when slack ws close

slack-message-changed.el
=> copy comment and file

slack-file-share-message.el, slack-file.el, slack-message-changed.el, slack-message-formatter.el, slack-message.el, slack-reaction.el, slack-room.el, slack-websocket.el
- display star and add `slack-message-add-star`, `slack-message-remove-star` commands.
- fix reactions to file or file-comment
=> Display star

slack-user.el
=> display_name_normalized is in profile

slack-file-share-message.el, slack-file.el, slack-room-buffer.el
=> Toggle email expand

slack-websocket.el
fix ignoring reaction to file which is not stored locally
=> Fix reaction to file

slack-websocket.el
close conn if error occured while `websocket-open`
=> Error handler for slack ws open

slack-thread.el
Appart from RET, left-click also brings you to the thread.
=> make threads clickable

slack-buffer.el, slack-file-info-buffer.el, slack-file-list-buffer.el, slack-message-buffer.el, slack-message-formatter.el, slack-message.el, slack-room.el, slack-search-result-buffer.el, slack-stars-buffer.el, slack-team.el, slack-websocket.el
add team level option `mark-as-read-immediately`.
=> Smart marker update

slack-message-buffer.el
fix below
1. `slack-buffer-last-read` returns `"0"`
2. call `slack-buffer-update-mark`timer with ts `"2"`
3. call `slack-buffer-update-mark`timer with ts `"1"` immediately
timer executed in 2 cancelled by 3
=> prevent timer canceled by smaller timestamp

README.md
Thanks for `emacs-slack`, I allowed myself to add some aesthetic and content details for the README.
=> Add modifications for a better README

slack-buffer.el, slack-file-comment.el, slack-file-info-buffer.el, slack-file-share-message.el, slack-file.el, slack-message-buffer.el, slack-message-formatter.el, slack-reaction.el
close #316 
need `cursor-sensor-mode`
=> Display reaction description

slack-buffer.el, slack-file-comment.el, slack-file-info-buffer.el, slack-file-share-message.el, slack-file.el, slack-message-buffer.el, slack-message-formatter.el, slack-message-reaction.el, slack-message.el, slack-reaction.el
=> Toggle reaction

slack-buffer.el
=> search single backtick and triple backtick

slack-buffer.el, slack-message.el
=> Disable buttonize in code blocks

slack-buffer.el, slack-file.el, slack-message-buffer.el, slack-thread-message-buffer.el
- call `slack-file-upload` from thread buffer
=> Upload file into thread

slack-websocket.el, slack.el
=> Fix typing timer

slack-buffer.el, slack-message-buffer.el, slack-search-result-buffer.el
=> Fix tracked p

slack-file.el, slack-group.el, slack-util.el
=> Fix multiple select

slack-websocket.el
=> Fix slack user typing

helm-slack.el, slack-buffer.el, slack-dialog-edit-element-buffer.el, slack-file.el, slack-message-buffer.el, slack-message-edit-buffer.el, slack-message-editor.el, slack-message-formatter.el, slack-message-share-buffer.el, slack-message.el, slack-room-message-compose-buffer.el, slack-room.el, slack-star.el, slack-stars-buffer.el, slack-thread-message-compose-buffer.el, slack-thread.el, slack-user-profile-buffer.el, slack-util.el, slack-websocket.el
=> remove header and blankline in `slack-buffer-insert`

slack-conversations.el, slack-message-buffer.el, slack-message-sender.el, slack-room-message-compose-buffer.el
https://github.com/yuya373/emacs-slack/issues/362
=> Auto join channel when send message

slack-buffer.el, slack-conversations.el, slack-message-buffer.el, slack-message-formatter.el, slack-message-sender.el, slack-room-message-compose-buffer.el
https://github.com/yuya373/emacs-slack/issues/362
=> Link channel name

slack-websocket.el
=> change log level to error

slack-buffer.el
close https://github.com/yuya373/emacs-slack/issues/367
=> Fix add face lazy

slack-all-threads-buffer.el, slack-conversations.el, slack-message-buffer.el, slack-room.el, slack-team.el, slack-thread-message-buffer.el, slack-thread.el, slack.el
- add command `slack-all-threads`
- add load more button to slack-thread-messages-buffer
=> Thread pagination

.travis.yml, slack-team.el, slack-websocket.el, slack.el
close https://github.com/yuya373/emacs-slack/issues/374
=> Fix slack ws close

helm-slack.el, slack-message-buffer.el, slack-unread.el, slack.el
- add command `slack-all-unreads`
- add command `helm-slack-unreads`
=> Add slack unread

slack-room-buffer.el, slack-thread.el
- add command `slack-message-follow`
- add command `slack-message-unfollow`
=> Add thread follow unfollow

slack-action.el, slack-message-buffer.el, slack-message-share-buffer.el, slack-message.el, slack-reminder.el, slack-room-buffer.el, slack-thread.el, slack-websocket.el
add some builtin actions to `slack-message-run-action`
=> Add actions to slack message run action

helm-slack.el, slack-all-threads-buffer.el, slack-channel.el, slack-conversations.el, slack-file-list-buffer.el, slack-file.el, slack-group.el, slack-im.el, slack-message-buffer.el, slack-room-buffer.el, slack-room.el, slack-stars-buffer.el, slack-team.el, slack-user.el, slack-websocket.el
use rest of conversations apis
=> Use conversations api

helm-slack.el, slack-authorize.el, slack-conversations.el, slack-im.el, slack-log.el, slack-message-buffer.el, slack-message-sender.el, slack-team.el, slack-thread-message-buffer.el, slack-user.el, slack-websocket.el
use `presence_sub` to get user presence
=> Fix presence subscription

slack-room.el
(I find the default hard to distinguish from read rooms)
=> Customizable face for unread rooms when selecting channels

slack-websocket.el
Reverts yuya373/emacs-slack#401
=> Revert "Close connection when websocket open failed"

slack-message-buffer.el
use `cons` instead of `list`, use `cdr-safe`
=> fix user is not plist

helm-slack.el, slack-all-threads-buffer.el, slack-conversations.el, slack-counts.el, slack-group.el, slack-im.el, slack-message-buffer.el, slack-message-notification.el, slack-modeline.el, slack-room.el, slack-team.el, slack-thread-message-buffer.el, slack-thread.el, slack-websocket.el, slack.el
=> Fix has unreads and mention count

slack-emoji.el, slack-message-buffer.el, slack-message-reaction.el, slack-request.el, slack-room-buffer.el, slack-team.el, slack-user.el
close https://github.com/yuya373/emacs-slack/issues/416
filter emojis by [this](https://stackoverflow.com/a/39654939) method and `emoji.list` api's return value.
=> Filter emojis

slack-message-buffer.el
=> fix missing team

slack-bot.el, slack-channel.el, slack-conversations.el, slack-group.el, slack-im.el, slack-message-buffer.el, slack-user.el
=> Conversations.view

slack-mrkdwn.el, test/run-test.el
close https://github.com/yuya373/emacs-slack/issues/430
=> Fix mrkdwn

slack-image.el, slack-message-buffer.el, slack-team.el, slack-util.el
animate gifs when cursor hovered on the message
```emacs-lisp
(slack-register-team
:default nil
:name "emacs-slack"
:token "xoxs-..."
;; snip
:animate-image t)
```
=> Animate gif

slack-group.el
=> Fix creator type

slack-message-buffer.el
close https://github.com/yuya373/emacs-slack/issues/448
=> call `slack-thread-message-update-buffer` always

slack-file-info-buffer.el, slack-file-list-buffer.el, slack-file.el, slack-message-reaction.el, slack-team.el, slack-websocket.el
- use hashtable to store files
- display file content
=> Use hashtable for files

slack-file.el, slack-request.el, slack-team.el, slack-typing.el, slack-websocket.el
add max-height, max-width to spec
=> Fix thumbnail spec

slack-file.el, slack-request.el, slack-team.el, slack-typing.el, slack-user-message.el, slack-util.el, slack-websocket.el
=> Fix status precence

slack-websocket.el
1. set ping check timer
2. send ping
1. send ping 
2. set ping check timer
1. set next ping timer
2. cancel ping check timer
1. cancel ping check timer
2. set next ping timer
=> fix eager timeout

slack-message-buffer.el, slack-websocket.el
close https://github.com/yuya373/emacs-slack/issues/463
=> Fix for non graphic

slack-websocket.el
close https://github.com/yuya373/emacs-slack/issues/460
=> Fix typing timer is invisible

slack-request.el
The current implementation keeps retrying in an infinite loop. This
takes resources in case the computer lost internet.
=> Adds max retry to failed requests

.gitignore, slack-buffer.el, slack-message-attachment-preview-buffer.el, slack-message-compose-buffer.el, slack-message-editor.el, slack-message-sender.el, slack-message-share-buffer.el, slack-request.el, slack-room-info-buffer.el, slack-room-message-compose-buffer.el, slack-team.el, slack-thread-message-buffer.el, slack-thread-message-compose-buffer.el, slack-websocket.el, test/test_all
- Add `slack-message-select-file`
- Bind <kbd>C-c</kbd> <kbd>C-f</kbd> to `slack-message-select-file` when `slack-message-compose-buffer-mode`
=> Multiple file upload

slack-message-event.el, slack-message.el, slack-thread.el
=> Thread replies removed from api response

slack-buffer.el
Oftentimes I make screenshot with flameshot and upload it to native slack client
with simple C-v. This PR adds the same feature to emacs-slack.
=> Add slack-clipboard-image-upload function.

docker-compose.yml, slack-image.el, test/run-test.el
=> Fix slack-image-path

slack-pkg.el, slack.el
ts-now was added by d7508a529c60d54f6a09d93575ff6aa2439b8fdc
=> add ts required package to resolve #593

slack-request.el
This should improve the experience for enterprise Slack users.
=> Expand notes about enterprise/team tokens and update team token list
